package pl.ene.ws.security.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-07-02T22:42:43.325+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", name = "ServiceIface")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceIface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", className = "pl.ene.ws.security.test.SayHelloType")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", className = "pl.ene.ws.security.test.SayHelloResponseType")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy")
        java.lang.String name
    );
}
