package pl.ene.testwebapp.domain;

// Generated 2007-11-19 15:34:54 by Hibernate Tools 3.2.0.b9

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * UirDefKryt generated by hbm2java
 */
@Entity  
@Table(name = "test_table")
// brak sekwencji
public class TestEntity implements Serializable {

	private static final long serialVersionUID = -7876407749335822008L;
	private Integer id;
	private String object;
	private String code;
	
	public TestEntity() {
	}

	public TestEntity(Integer id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	
	@Column(name = "object", nullable = false, length = 50)
	public String getObject()
  {
    return object;
  }

  public void setObject(String object)
  {
    this.object = object;
  }

  @Column(name = "code", nullable = false)
  public String getCode()
  {
    return code;
  }

  public void setCode(String code)
  {
    this.code = code;
  }

}
