package pl.ene.ws.security.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-07-02T22:42:43.410+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "SecurityService", 
                  wsdlLocation = "file:/D:/programming/hosting/java-prototype-ene/trunk/ws-security/src/main/webapp/WEB-INF/wsdl/Hello.wsdl",
                  targetNamespace = "http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy") 
public class SecurityService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", "SecurityService");
    public final static QName SecurityServicePort = new QName("http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", "SecurityServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/programming/hosting/java-prototype-ene/trunk/ws-security/src/main/webapp/WEB-INF/wsdl/Hello.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SecurityService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/programming/hosting/java-prototype-ene/trunk/ws-security/src/main/webapp/WEB-INF/wsdl/Hello.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SecurityService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SecurityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SecurityService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SecurityService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SecurityService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns ServiceIface
     */
    @WebEndpoint(name = "SecurityServicePort")
    public ServiceIface getSecurityServicePort() {
        return super.getPort(SecurityServicePort, ServiceIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceIface
     */
    @WebEndpoint(name = "SecurityServicePort")
    public ServiceIface getSecurityServicePort(WebServiceFeature... features) {
        return super.getPort(SecurityServicePort, ServiceIface.class, features);
    }

}
